# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Crawling

on:
  schedule:
    - cron: "0 0,12 * * *" # 매일 정오와 자정에 실행
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install newspaper3k
          pip install pandas
          pip install schedule

      - name: Run crawling.py
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python SubwayNewsCrawling.py

      - name: Commits and Push
        run: |
          git config --local user.email "gus1043@gmail.com"
          git config --local user.name "Auto_Scraping_Name"
          git add .
          git diff --cached --quiet || git commit -m "Auto - Update Emergencybell News data with Crawling"
          git pull --no-rebase origin main # 최신 변경 사항 가져오기 (병합)
          git push origin main # 변경된 내용 푸시
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
