# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Crawling

on:
  schedule:
    - cron: '*/5 * * * *' #5분 간격으로 실행하는 거 '0 0,12 * * *' 이거면 정오랑 자
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          
      - name: Install dependencies
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python -m pip install --upgrade pip
          pip install newspaper3k
          pip install schedule
          
      - name: Run crawling.py
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python BusNewsCrawling.py
          python CctvNewsCrawling.py
          python SubwayNewsCrawling.py
          python SecuritylightNewsCrawling.py
          python PoliceNewsCrawling.py
          python EmergenbellNewsCrawling.py
