# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Crawling

on:
  schedule:
    - cron: '0 */3 * * *' # 3시간 마다 실행
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install newspaper3k
          pip install pandas
          pip install schedule

      - name: Run crawling.py
        working-directory: CarrotMarket/JiHyeon/AutoCrawling/
        run: |
          python BusNewCrawling.py
          python CctvNewsCrawling.py
          python SubwayNewsCrawling.py
          python SecuritylightNewsCrawling.py
          python PoliceNewsCrawling.py
          python EmergenbellNewsCrawling.py

      - name: Commits and Push
        run: |
          git config --local user.email "gus1043@gmail.com"
          git config --local user.name "Auto_Scraping_Name"
          git add .
          git diff --cached --quiet || git commit -m "Auto - Update data with Scraping"
          git pull origin main # 최신 변경 사항 가져오기
          git push origin main # 변경된 내용 푸시
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Upload CSV
        run: |
          echo "${{ secrets.HADOOP_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          mkdir -p ~/.ssh
          echo "Executing ssh-keyscan..."
          ssh-keyscan -p 22 -H 104 >> ~/.ssh/known_hosts 2>&1 || echo "ssh-keyscan failed"
          echo "Executing scp..."
          scp -v -i key.pem -P 22 "CarrotMarket/JiHyeon/AutoCrawling/*.csv" maria_dev@104:~
          echo "Executing ssh..."
          ssh -v -i key.pem -p 22 maria_dev@104 "for file in ~/*.csv; do hdfs dfs -put -f \$file /home/maria_dev/crawling/; done"
        env:
          HADOOP_SSH_PRIVATE_KEY: ${{ secrets.HADOOP_SSH_PRIVATE_KEY }}

