# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Send Crawled Files via SSH

on:
  schedule:
    - cron: '0 */12 * * *'  # 매 12시간마다 실행
jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   SECRET_API_KEY: ${{ secrets.COMMAND }}
    permissions:
      contents: read
      packages: write
    steps:
        
    - name: SSH into Deployment Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        proxy_host: ${{ secrets.PROXY_SERVER_HOST }}
        proxy_port: ${{ secrets.PROXY_SERVER_PORT }}
        proxy_username: ${{ secrets.PROXY_SERVER_USERNAME }}
        proxy_key: ${{ secrets.SSH_KEY }}
        script: |
          bash ~/news/getNewsAndCopyToHDFS.sh
          bash ~/wordcount/wordcountToHBASE.sh
